### ISSUE TITLE
Incorrect diff parsing

### ISSUE THREAD

**Issue by lamtev** [ACCULA/accula#266]
Incorrect diff parsing when file looks like three way merge hunk:
```yaml
@@ -59,4 +59,4 @@ checks:
       threshold: 10 # Have pattern-matching-like code
 exclude_patterns: 
 - "**/*.svg" # <- looks like deletion in three way merge hunk
-- "test/**/*.java"+- "src/test/"
```
